import { initializePrivateConnection } from "../../src/custom/private-connection.js";
import { initializeStorageUpgrade } from "../../src/custom/storage-upgrade.js";
import "../storage-migration/entry.js";
import { initializeOptionMatch } from "../../src/custom/option-match.js";
import { initializeProfileAnswers } from "../../src/custom/profile-answers.js";
import "../../src/custom/response-contract.js";
import { initializeDocumentStore } from "../../src/custom/document-store.js";
import { initializeJobMatchRules } from "../../src/custom/job-match-rules.js";
import { initializeJobMatch } from "../../src/custom/job-match.js";
import { initializeAvailabilityRules } from "../../src/custom/availability-rules.js";
import { initializeSync } from "../../src/custom/sync.js";

import { initializeResponseScope } from "../../src/custom/response-scope.js";
import { initializeManagementModel } from "../../src/custom/management-model.js";
import { initializeManagementSync } from "../../src/custom/management-sync.js";
import { initializeTabProfiles } from "../../src/custom/tab-profiles.js";
import { initializeAutomaticBackground } from "../../src/custom/automatic-background.js";
import "../../src/custom/review-background.js";
import { initializeControlConfig } from "../../src/custom/control-config.js";
import { initializeHistoryBackground } from "../../src/custom/history-background.js";
import { initializeReproCase } from "../../src/custom/repro-case.js";
import { initializeReproBackground } from "../../src/custom/repro-background.js";
import { initializeControlBackground } from "../../src/custom/control-background.js";
import { initializeDiagnosticsBackground } from "../../src/custom/diagnostics-background.js";
import { initializeApplicationQueue } from "../../src/custom/application-queue.js";
import { initializeQueueBackground } from "../../src/custom/queue-background.js";
import { initializeSubmissionBackground } from "../../src/custom/submission-background.js";
import "../../source/background-api.js";
import "../../source/runtime-registration.js";
initializePrivateConnection();
initializeStorageUpgrade();
initializeOptionMatch();
initializeProfileAnswers();

initializeDocumentStore();
initializeJobMatchRules();
initializeJobMatch();
initializeAvailabilityRules();
initializeSync();

initializeResponseScope();
initializeManagementModel();
initializeManagementSync();
initializeTabProfiles();
initializeAutomaticBackground();
initializeControlConfig();
initializeHistoryBackground();
initializeReproCase();
initializeReproBackground();
initializeControlBackground();
initializeDiagnosticsBackground();
initializeApplicationQueue();
initializeQueueBackground();
initializeSubmissionBackground();
import { JobsSync } from "../../src/custom/sync.js";
import { JobsManagementSync } from "../../src/custom/management-sync.js";
void JobsSync.ready.then(() => JobsManagementSync.sync());
