import { initializeQueuePage } from "../../src/custom/queue-page.js";
import { initializePageActions } from "../../src/custom/page-actions.js";
import { initializeJobMatchRules } from "../../src/custom/job-match-rules.js";
import { initializeJobMatch } from "../../src/custom/job-match.js";
import { initializeAvailabilityRules } from "../../src/custom/availability-rules.js";
import { initializeJobAvailability } from "../../src/custom/job-availability.js";
import { initializeAppliedStatus } from "../../src/custom/applied-status.js";
import { initializeOptionMatch } from "../../src/custom/option-match.js";
import { initializeProfileAnswers } from "../../src/custom/profile-answers.js";
import "../../src/custom/response-contract.js";
import { initializeAnswerResolver } from "../../src/custom/answer-resolver.js";
import { initializeControlConfig } from "../../src/custom/control-config.js";
import { initializeDomWait } from "../../src/custom/dom-wait.js";
import { initializeReproCase } from "../../src/custom/repro-case.js";
import { initializeDiagnostics } from "../../src/custom/diagnostics.js";
import { initializeAnswerMemory } from "../../src/custom/answer-memory.js";
import { initializeAshbyControls } from "../../src/custom/ashby-controls.js";
import { initializeOracleControls } from "../../src/custom/oracle-controls.js";
import { initializePlatformConfig } from "../../src/custom/platform-config.js";
import { initializeControlFields } from "../../src/custom/control-fields.js";
import { initializeManualAnswer } from "../../src/custom/manual-answer.js";
import { initializeGreenhouseControls } from "../../src/custom/greenhouse-controls.js";
import { initializeWorkdayControls } from "../../src/custom/workday-controls.js";
import { initializeIcimsControls } from "../../src/custom/icims-controls.js";
import { initializeSuccessfactorsControls } from "../../src/custom/successfactors-controls.js";
import { initializeMenuControls } from "../../src/custom/menu-controls.js";
import { initializeLegacySelectControls } from "../../src/custom/legacy-select-controls.js";
import { initializeAtsChoiceControls } from "../../src/custom/ats-choice-controls.js";
import { initializeShadowControls } from "../../src/custom/shadow-controls.js";
import { initializeTagControls } from "../../src/custom/tag-controls.js";
import { initializeDisclosureControls } from "../../src/custom/disclosure-controls.js";
import { initializeAriaControls } from "../../src/custom/aria-controls.js";
import { initializeTeslaControls } from "../../src/custom/tesla-controls.js";
import { initializeFormPipeline } from "../../src/custom/form-pipeline.js";
import { initializeOperationContext } from "../../src/custom/operation-context.js";
import { initializeControlContent } from "../../src/custom/control-content.js";
import { initializeReviewPresenter } from "../../src/custom/review-presenter.js";
import { initializeAiReview } from "../../src/custom/ai-review.js";
import { initializeAutomaticFill } from "../../src/custom/automatic-fill.js";
import { watchPage } from "../content/shell.js";
if (!globalThis.__jobsNativePage) {
  globalThis.__jobsNativePage = true;
  initializeQueuePage();
  initializePageActions();
  initializeJobMatchRules();
  initializeJobMatch();
  initializeAvailabilityRules();
  initializeJobAvailability();
  initializeOptionMatch();
  initializeProfileAnswers();

  initializeAnswerResolver();
  initializeControlConfig();
  initializeDomWait();
  initializeReproCase();
  initializeDiagnostics();
  initializeAnswerMemory();
  initializeAshbyControls();
  initializeOracleControls();
  initializePlatformConfig();
  initializeControlFields();
  initializeManualAnswer();
  initializeGreenhouseControls();
  initializeWorkdayControls();
  initializeIcimsControls();
  initializeSuccessfactorsControls();
  initializeMenuControls();
  initializeLegacySelectControls();
  initializeAtsChoiceControls();
  initializeShadowControls();
  initializeTagControls();
  initializeDisclosureControls();
  initializeAriaControls();
  initializeTeslaControls();
  initializeFormPipeline();
  initializeOperationContext();
  initializeControlContent();
  initializeReviewPresenter();
  initializeAiReview();
  initializeAutomaticFill();
  initializeAppliedStatus();
  watchPage();
}
